"""The Score, U19: README header visuals and the social image (DESIGN.md A5, A12).

Static checks on committed files only: no browser, no network, no provider.
The images themselves are regenerated by scripts/render-readme-assets.py from
the key-free fixture corpus, and the browser suite checks that path.
"""

from __future__ import annotations

import re
import struct
import unittest
from pathlib import Path

from tests.test_copy_rules import DASH_EMOJI, lint_text

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"
README = ROOT / "README.md"
BRAND = ROOT / "ui" / "brand"

SOCIAL_BUDGET = 150 * 1024
SCREENSHOT_BUDGET = 260 * 1024
TOKEN_INKS = {"paper": "#121417", "stage": "#ECEEF0"}


def png_size(path: Path) -> tuple[int, int]:
    head = path.read_bytes()[:24]
    assert head[:8] == b"\x89PNG\r\n\x1a\n", path
    return struct.unpack(">II", head[16:24])


class TestReadme(unittest.TestCase):
    text = README.read_text(encoding="utf-8")

    def test_no_emoji_or_dash(self):
        self.assertEqual(DASH_EMOJI.findall(self.text), [])
        self.assertEqual(lint_text(self.text), [])

    def test_every_local_image_exists(self):
        paths = re.findall(r'(?:src|srcset)="([^"#]+)"', self.text)
        paths += re.findall(r"!\[[^\]]*\]\(([^)\s]+)\)", self.text)
        local = [p for p in paths if not p.startswith(("http://", "https://"))]
        self.assertTrue(local, "README references no local images")
        for p in local:
            self.assertTrue((ROOT / p).is_file(), p)

    def test_header_is_a_picture_with_light_and_dark_lockups(self):
        head = self.text.split("## ", 1)[0]
        self.assertIn("<picture>", head)
        self.assertRegex(head, r'media="\(prefers-color-scheme: dark\)"\s+srcset="docs/assets/lockup-dark\.svg"')
        self.assertIn("docs/assets/lockup-light.svg", head)
        self.assertNotIn("social.png", head)

    def test_screenshot_is_referenced_with_alt_text(self):
        m = re.search(r'<img src="docs/assets/observatory-paper\.png" alt="([^"]{20,})"', self.text)
        self.assertIsNotNone(m, "paper Pairings screenshot needs real alt text")

    def test_images_have_dimensions_for_layout(self):
        for m in re.finditer(r"<img [^>]*>", self.text):
            self.assertIn("width=", m.group(), m.group())


class TestLockups(unittest.TestCase):
    def test_lockups_match_the_brand_lockup_in_token_inks(self):
        brand = (BRAND / "lockup-horizontal.svg").read_text()
        for theme in ("light", "dark"):
            svg = (ASSETS / f"lockup-{theme}.svg").read_text()
            ink = TOKEN_INKS["paper" if theme == "light" else "stage"]
            self.assertNotIn("currentColor", svg)
            self.assertEqual(svg, brand.replace("currentColor", ink))
            self.assertEqual(set(re.findall(r'fill="(#[0-9A-Fa-f]{6})"', svg)), {ink})
            self.assertEqual(DASH_EMOJI.findall(svg), [])


class TestImages(unittest.TestCase):
    def test_social_is_1280x640_within_budget(self):
        p = ASSETS / "social.png"
        self.assertEqual(png_size(p), (1280, 640))
        self.assertLessEqual(p.stat().st_size, SOCIAL_BUDGET, p.stat().st_size)

    def test_observatory_screenshot_is_paper_1440_within_budget(self):
        p = ASSETS / "observatory-paper.png"
        w, h = png_size(p)
        self.assertEqual(w, 1440)
        self.assertTrue(600 <= h <= 1400, h)
        self.assertLessEqual(p.stat().st_size, SCREENSHOT_BUDGET, p.stat().st_size)

    def test_social_template_is_static_tokens_only(self):
        src = (ROOT / "ui" / "og" / "social.html").read_text()
        self.assertEqual(lint_text(src), [])
        self.assertNotRegex(src, r"#[0-9A-Fa-f]{6}\b", "raw hex outside tokens")
        self.assertIn("../tokens.css", src)
        self.assertNotIn("https://", src.replace("http://www.w3.org", ""))


try:
    import playwright.sync_api  # noqa: F401
    HAS_PLAYWRIGHT = True
except ImportError:
    HAS_PLAYWRIGHT = False


@unittest.skipUnless(HAS_PLAYWRIGHT, "playwright not installed (pip install 'orchestral[shots]')")
class TestRenderScript(unittest.TestCase):
    """The committed images can be regenerated, within the same budgets, with no key."""

    def test_render_matches_the_budgets(self):
        import importlib.util
        import os
        import tempfile
        from unittest.mock import patch

        spec = importlib.util.spec_from_file_location("render_readme", ROOT / "scripts" / "render-readme-assets.py")
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        with tempfile.TemporaryDirectory() as tmp, patch.dict(
                os.environ, {k: v for k, v in os.environ.items() if not k.endswith("_API_KEY")}, clear=True):
            files = {p.name: p for p in mod.render(Path(tmp))}
            self.assertEqual(png_size(files["social.png"]), (1280, 640))
            self.assertLessEqual(files["social.png"].stat().st_size, SOCIAL_BUDGET)
            self.assertEqual(png_size(files["observatory-paper.png"])[0], 1440)
            self.assertLessEqual(files["observatory-paper.png"].stat().st_size, SCREENSHOT_BUDGET)


if __name__ == "__main__":
    unittest.main()
